### ISSUE TITLE
Problem setting up the project

### ISSUE THREAD

**Issue by ferangulo99** [minhpq331/jitsi-scalable-helm#4]
Helllo, I'm having some truble settting up your project. Im doing it in DigitalOcean's clusters. The problem is with the ingress. i´ve got my web running so i can connect without any  problem to the home webpage. 
Whenever i try to access into a room i get this error:
- Firefox no puede establecer una conexión con el servidor en wss://texxxxxxxx.xxxxxxxx.xxxxxx.com/xmpp-websocket?room=hjghj.

Which means that firefox cannot stablish conexion with that server (domain is hidden). As you can see the url is not starting with wss://ws.texxx.xxx.xxxx.com but i don´t really know why.

Thank you very much in advance, this is a very helpful work you´ve done in this repository.

**Comment by minhpq331** [comment]
@ferangulo99 Hello, that means the web cannot connect to your xmpp websocket server. Please note that there are 2 websocket servers:
- XMPP websocket (which show on your error). This websocket by default run on same domain as the web. So if your web url is `https://myjitsi.com` then XMPP wss url is `wss://myjitsi.com/xmpp-websocket`
- JVB websocket (which point to jvb service with custom domain like `wss://ws.myjitsi.com`.

Can you provide more detail about the error? You can run this command to check if your ws url is correct:

```
curl "https://myjitsi.com/xmpp-websocket?room=abc" -vvv
```
myjitsi.com is your web url. This command should return http code 403 with body: Denied.

**Comment by ferangulo99** [comment]
`   Trying 1xxx.xxx.xxx.xxx:xxx...
* TCP_NODELAY set
* Connected to xxxx.xxxx.xxxx.com (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Jan 27 11:34:32 2022 GMT
*  expire date: Jan 27 11:34:32 2023 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x563ba8e1cc80)
> GET /xmpp-websocket?room=abc HTTP/2
> Host: xxxx.xxxx.xxxxxx.com
> user-agent: curl/7.68.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: openresty/1.15.8.2
< date: Thu, 27 Jan 2022 11:49:14 GMT
< content-type: text/html
< vary: Accept-Encoding
< strict-transport-security: max-age=15724800; includeSubDomains
< vary: Accept-Encoding
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< permissions-policy: interest-cohort=()
<!DOCTYPE html><html><head><title>Websocket</title></head><body>
			<p>It works! Now point your WebSocket client to this URL to connect to Prosody.</p>
* Connection #0 to host xxxxx.xxxxx.xxxxx.com left intact  `


This is the output when i run that command. Still not being able to access a room.

**Comment by ferangulo99** [comment]
Here is some more info about the error.
![InkedMicrosoftTeams-image_LI](https://user-images.githubusercontent.com/98464025/151356037-0107a1c4-aebd-4dbf-83e0-325fa735e75f.jpg)

**Comment by ferangulo99** [comment]
I have just realized  it is a certificate problem.
Thank you very much for your response. i am closing the issue.
