### ISSUE TITLE
video disabled when 3rd person enters the room [urgent]

### ISSUE THREAD

**Issue by bharath-naik** [minhpq331/jitsi-scalable-helm#7]
hi @minhpq331 , since then jitsi is working fine but from last few days when a 3rd person joins video is disabled. need urgent help.
For P2P there is no issue.
There was a change in firewalls since then.
![image](https://user-images.githubusercontent.com/20774548/160820559-31be8a0f-1623-4226-8339-c920e56654c5.png)

**Comment by minhpq331** [comment]
@bharath-naik I've check your site and found your certificate for ws.xxx.xxx was expired. That's why your browser cannot connect to ws server.

**Comment by bharath-naik** [comment]
solved thanks.. how did i miss this 😐
